### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by scul81** [AndrewBudziszek/bitcoin-ticker-esp32#1]
Hi,

I am trying to load this code onto my board but I have a number of issues.

First of all which HTTPClient library is meant to be used? The exact libraries aren't specified and there are several ones.

I'm getting the following errors
`D:\Data\Docs\Arduino\CryptoTicker\CryptoTicker.ino: In function 'void setup()':

CryptoTicker:132:14: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]

  132 |   WiFi.begin(ssid, password);

      |              ^~~~

      |              |

      |              const char*

In file included from D:\Data\Docs\Arduino\CryptoTicker\CryptoTicker.ino:9:

C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:79:21: note:   initializing argument 1 of 'int WiFiClass::begin(char*, const char*)'

   79 |     int begin(char* ssid, const char *passphrase);

      |               ~~~~~~^~~~

D:\Data\Docs\Arduino\CryptoTicker\CryptoTicker.ino: In function 'void loop()':

CryptoTicker:156:23: error: 'class HttpClient' has no member named 'GET'

  156 |   int httpCode = http.GET();                                                            //Get crypto price from API

      |                       ^~~

CryptoTicker:158:58: error: 'class HttpClient' has no member named 'getString'; did you mean 'readString'?

  158 |   DeserializationError error = deserializeJson(doc, http.getString());

      |                                                          ^~~~~~~~~

      |                                                          readString

CryptoTicker:173:8: error: 'class HttpClient' has no member named 'end'

  173 |   http.end();

      |        ^~~

CryptoTicker:178:30: error: 'class HttpClient' has no member named 'GET'

  178 |   int historyHttpCode = http.GET();

      |                              ^~~

CryptoTicker:179:72: error: 'class HttpClient' has no member named 'getString'; did you mean 'readString'?

  179 |   DeserializationError historyError = deserializeJson(historyDoc, http.getString());

      |                                                                        ^~~~~~~~~

      |                                                                        readString

CryptoTicker:234:8: error: 'class HttpClient' has no member named 'end'

  234 |   http.end();                                                                           //End the WiFi connection

      |        ^~~

CryptoTicker:235:3: error: 'esp_sleep_enable_timer_wakeup' was not declared in this scope

  235 |   esp_sleep_enable_timer_wakeup(900000000);                                             //Sleep for 15 minutes

      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

exit status 1

invalid conversion from 'const char*' to 'char*' [-fpermissive]`

Secondly, I know it may not be entirely compatible but I am trying to run this off a NodeMCU unit (ESP12E) which should be possible. Do you have any idea how to identify the correct pin-outs for the SCK/SDA pins?

**Comment by AndrewBudziszek** [comment]
Hi, I'm sorry that you're having issues. You can identify the correct pin-outs for the SCK/SDA pins by looking up the manufacturer's specs sheet. This will not work on an ESP8266(ESP12E). You might want to check out this other repo that I have for the ESP8266 as they require different libs. 

https://github.com/SonnyBrooks/bitcoin-ticker-esp8266

**Comment by AndrewBudziszek** [comment]
Closing due to user using incompatible device not relevant to this code.
