### ISSUE TITLE
HTTPClient (which one to use)

### ISSUE THREAD

**Issue by quintendewilde** [AndrewBudziszek/bitcoin-ticker-esp32#2]
I get this error with the arduino HTTPClient library and the Adrian McEwen version

`CryptoTicker:35:1: error: 'HTTPClient' does not name a type; did you mean 'NTPClient'?
   35 | HTTPClient http;
      | ^~~~~~~~~~
      | NTPClient
/Users/quintendewilde/Downloads/CryptoTicker/CryptoTicker.ino: In function 'void setup()':
CryptoTicker:134:14: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  134 |   WiFi.begin(ssid, password);
      |              ^~~~
      |              |
      |              const char*
In file included from /Users/quintendewilde/Downloads/CryptoTicker/CryptoTicker.ino:11:
/private/var/folders/sd/8sktr7393sdgg1bpx9cd6nt40000gn/T/AppTranslocation/E6CF2EA4-AA26-4CBD-B7A8-ABA8AEE8F46E/d/Arduino.app/Contents/Java/libraries/WiFi/src/WiFi.h:79:21: note:   initializing argument 1 of 'int WiFiClass::begin(char*, const char*)'
   79 |     int begin(char* ssid, const char *passphrase);
      |               ~~~~~~^~~~
/Users/quintendewilde/Downloads/CryptoTicker/CryptoTicker.ino: In function 'void loop()':
CryptoTicker:157:3: error: 'http' was not declared in this scope
  157 |   http.begin(url);
      |   ^~~~
CryptoTicker:237:3: error: 'esp_sleep_enable_timer_wakeup' was not declared in this scope
  237 |   esp_sleep_enable_timer_wakeup(900000000);                                             //Sleep for 15 minutes
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
exit status 1
'HTTPClient' does not name a type; did you mean 'NTPClient'?
`

**Comment by quintendewilde** [comment]
I get lot's of other issues. All based (In my opinion) with using the wrong libraries..

**Comment by AndrewBudziszek** [comment]
The code as provided with the libraries mentioned is working as expected on my end. Can you verify that you're using an ESP-32 and NOT an ESP-8266. This particular repo does NOT work with the ESP-8266.

**Comment by quintendewilde** [comment]
Oh! My apologies, didn't look at the correct repository!
